theme: jekyll-theme-time-machine
title: Docusaurus
description: Docusaurus is an open-source and can be used for free under the MIT License. It has a growing community of contributors and users, and is actively maintained and developed.
